import { getResearchTask, type ResearchTaskId } from "./research-task";
import type { CardRelation, ReasoningCard } from "./rmw-types";

export function createInitialCards(taskId: ResearchTaskId): ReasoningCard[] {
  const task = getResearchTask(taskId);
  return [
    {
      id: "goal",
      cardType: "goal",
      goalLevel: "main",
      content: {
        "zh-CN": `形成可研究的问题框架：${task.label["zh-CN"]}`,
        en: `Develop a researchable framing: ${task.label.en}`,
      },
      detail: task.question,
      nextAction: {
        "zh-CN": "先校准候选卡片，再回到尚未验证的假设",
        en: "Calibrate the candidate cards, then return to the unverified hypothesis",
      },
      confidence: 94,
      status: "active",
      priority: "pinned",
      riskTags: [],
      sourceRefs: [{ id: `${task.code.toLowerCase()}1`, kind: "material", label: `材料 ${task.code}1`, anchor: `${task.code.toLowerCase()}1` }],
      revision: 1,
      generatedBy: "llm",
      reviewedByResearcher: false,
    },
    {
      id: "goal-compare",
      cardType: "goal",
      goalLevel: "subgoal",
      parentGoalId: "goal",
      content: { "zh-CN": "比较至少两个候选问题框架", en: "Compare at least two candidate problem framings" },
      detail: { "zh-CN": "候选框架应分别说明证据、机制与可能导向的干预。", en: "Each framing should state its evidence, mechanism, and implied intervention." },
      nextAction: { "zh-CN": "核对两个框架分别使用了哪些材料", en: "Check which materials support each framing" },
      confidence: 82,
      status: "active",
      priority: "normal",
      riskTags: ["inferred"],
      sourceRefs: [],
      revision: 1,
      generatedBy: "llm",
      reviewedByResearcher: false,
    },
    {
      id: "goal-hypotheses",
      cardType: "goal",
      goalLevel: "subgoal",
      parentGoalId: "goal",
      content: { "zh-CN": "形成至少两个可验证假设", en: "Form at least two testable hypotheses" },
      detail: { "zh-CN": "假设需要区分观察到的相关关系与尚未验证的因果机制。", en: "Hypotheses must distinguish observed associations from unverified causal mechanisms." },
      nextAction: { "zh-CN": "把每个假设写成可被证伪的表达", en: "Rewrite each hypothesis so it can be falsified" },
      confidence: 78,
      status: "active",
      priority: "normal",
      riskTags: ["inferred"],
      sourceRefs: [],
      revision: 1,
      generatedBy: "llm",
      reviewedByResearcher: false,
    },
    {
      id: "goal-study",
      cardType: "goal",
      goalLevel: "subgoal",
      parentGoalId: "goal",
      content: { "zh-CN": "规划可行的干预与验证方式", en: "Plan a feasible intervention and validation strategy" },
      detail: { "zh-CN": "研究设计必须尊重材料中的现实约束，并说明结果指标。", en: "The study design must respect the stated constraints and define outcome measures." },
      nextAction: { "zh-CN": "回到材料逐项检查约束", en: "Return to the materials and check every constraint" },
      confidence: 80,
      status: "active",
      priority: "normal",
      riskTags: ["inferred"],
      sourceRefs: [],
      revision: 1,
      generatedBy: "llm",
      reviewedByResearcher: false,
    },
    {
      id: "goal-scope",
      cardType: "goal",
      goalLevel: "suspended",
      parentGoalId: "goal",
      content: { "zh-CN": "是否扩展到更多地区或人群", en: "Whether to extend to additional areas or populations" },
      detail: { "zh-CN": "暂时挂起，先完成当前材料范围内的问题框架。", en: "Suspend this until the framing within the current evidence pack is complete." },
      confidence: 62,
      status: "active",
      priority: "normal",
      riskTags: ["inferred"],
      sourceRefs: [],
      revision: 1,
      generatedBy: "llm",
      reviewedByResearcher: false,
    },
    {
      id: "goal-long-term",
      cardType: "goal",
      goalLevel: "suspended",
      parentGoalId: "goal",
      content: { "zh-CN": "是否加入长期效果指标", en: "Whether to add long-term outcome measures" },
      detail: { "zh-CN": "先定义近期可观察结果，再决定长期追踪是否必要。", en: "Define near-term observable outcomes before deciding on longitudinal follow-up." },
      confidence: 60,
      status: "active",
      priority: "normal",
      riskTags: ["inferred"],
      sourceRefs: [],
      revision: 1,
      generatedBy: "llm",
      reviewedByResearcher: false,
    },
    {
      id: "uncertain",
      cardType: "hypothesis",
      content: { "zh-CN": "当前核心机制仍需结合你的 memo 与材料校准", en: "The core mechanism still needs calibration against your memo and the materials" },
      detail: { "zh-CN": "这是低置信度候选项；请编辑成你在第一阶段实际保留的不确定假设。", en: "This is a low-confidence candidate. Edit it to match the uncertainty you actually retained in Phase 1." },
      confidence: 35,
      status: "uncertain",
      priority: "pinned",
      riskTags: ["needs_verify", "inferred", "high_impact"],
      sourceRefs: [],
      revision: 1,
      generatedBy: "llm",
      reviewedByResearcher: false,
    },
    {
      id: "constraint",
      cardType: "constraint",
      content: { "zh-CN": "干预方案不得绕开材料给出的现实约束", en: "The intervention must not bypass constraints stated in the materials" },
      detail: { "zh-CN": "请回源核对具体限制，不要凭印象补充或删除约束。", en: "Return to the source text for the exact limits; do not add or remove constraints from memory." },
      confidence: 88,
      status: "active",
      priority: "normal",
      riskTags: [],
      sourceRefs: [{ id: `${task.code.toLowerCase()}4`, kind: "material", label: `材料 ${task.code}4`, anchor: `${task.code.toLowerCase()}4` }],
      revision: 1,
      generatedBy: "llm",
      reviewedByResearcher: false,
    },
    {
      id: "path",
      cardType: "path",
      content: { "zh-CN": "待校准：你在第一阶段排除的不可行方向", en: "Calibration needed: the infeasible direction you ruled out in Phase 1" },
      detail: { "zh-CN": "系统未在演示数据中可靠识别具体路径。请按你的实际推理编辑，不要直接接受占位内容。", en: "The demo trace did not reliably identify a specific path. Edit this to match your reasoning rather than accepting the placeholder." },
      confidence: 24,
      status: "uncertain",
      priority: "normal",
      riskTags: ["needs_verify", "inferred"],
      sourceRefs: [],
      revision: 1,
      generatedBy: "llm",
      reviewedByResearcher: false,
    },
    {
      id: "next",
      cardType: "next_action",
      content: { "zh-CN": "回到 memo 中的未验证点，核对材料并确定一个最小下一步", en: "Return to the unresolved point in the memo, check the materials, and choose one minimum next action" },
      detail: { "zh-CN": "先校准这张卡片，使其准确对应你中断前准备执行的动作。", en: "Calibrate this card so it matches the action you intended to take immediately before interruption." },
      confidence: 52,
      status: "uncertain",
      priority: "pinned",
      riskTags: ["needs_verify", "inferred"],
      sourceRefs: [],
      revision: 1,
      generatedBy: "llm",
      reviewedByResearcher: false,
    },
  ];
}

export const relations: CardRelation[] = [
  { id: "r0a", sourceCardId: "goal-compare", targetCardId: "goal", relationType: "supports" },
  { id: "r0b", sourceCardId: "goal-hypotheses", targetCardId: "goal", relationType: "supports" },
  { id: "r0c", sourceCardId: "goal-study", targetCardId: "goal", relationType: "constrains" },
  { id: "r1", sourceCardId: "constraint", targetCardId: "goal-study", relationType: "constrains" },
  { id: "r2", sourceCardId: "uncertain", targetCardId: "next", relationType: "leads_to" },
  { id: "r3", sourceCardId: "path", targetCardId: "goal", relationType: "rejects" },
];
